services:
  - type: web
    name: admin-dashboard-backend
    runtime: node
    plan: free

    branch: main
    autoDeploy: true

    buildCommand: npm install && npx prisma generate && npm run build

    startCommand: npx prisma migrate deploy && npm run start:prod

    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRES_IN
        value: 3600s

      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

      - key: CORS_ORIGIN
        sync: false

    healthCheckPath: /api/health